# Dockerfile — Hybrid AI Complaint Escalation System
# ─────────────────────────────────────────────────────────────────────
# Build:   docker build -t hybrid-ai-app .
# Run:     docker run -p 8000:8000 -e GEMINI_API_KEY=your_key hybrid-ai-app
# Test:    curl http://localhost:8000/health
# ─────────────────────────────────────────────────────────────────────

FROM python:3.11-slim   

# Set working directory
WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc g++ && \
    rm -rf /var/lib/apt/lists/*

# Copy requirements and install Python packages
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy application files
COPY *.py ./
COPY *.md ./
COPY *.json ./
COPY .env* ./

# Copy saved model files 
# These are generated by running the training scripts first:
#   python train_classical_model.py
#   python train_cnn_model.py
#   python train_rnn_model.py
COPY *.pkl ./
COPY *.keras ./

# Expose FastAPI port
EXPOSE 8000

# API key is passed as an environment variable at runtime
# Never hardcode API keys in Docker images
ENV GEMINI_API_KEY=""

# Run the FastAPI server
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
